version: "3.4"
services:

  nginx:
    image: cytomine/nginx:v1.4.0
    container_name: nginxTest
    hostname: nginxTest
    restart: unless-stopped
    volumes:
      - "./config/nginx/nginxCORS.conf:/usr/local/nginx/conf/nginx.conf"
    links:
      - "core:core"

  core:
    image: cytomine/core:try-to-fix-circular-dep-20220324212615-SNAPSHOT
    restart: unless-stopped
    volumes:
      - "./config/cytomineconfig.groovy:/usr/share/tomcat9/.grails/cytomineconfig.groovy"
      - "./config/addHosts.sh:/tmp/addHosts.sh"
    links:
      - "postgresql:postgresql"
      - "mongodb:mongodb"
      - "rabbitmq:rabbitmq"

  postgresql:
    image: cytomine/postgis:v2.0.0
    restart: unless-stopped

  mongodb:
    image: cytomine/mongodb:v1.1.2
    restart: unless-stopped

  rabbitmq:
    image: cytomine/rabbitmq:v1.1.2
    restart: unless-stopped
